version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - exptostd
    - govet
    - perfsprint
    # - tagalign
    - usestdlibvars
    - ineffassign
    - unused
    - prealloc
    - ineffassign
    - goconst
    # - makezero
    - nilerr
    - nilnesserr
    - nilnil