DROP trigger set_timestamp_user on "user";
DROP trigger set_timestamp_user_session on "user_session";
DROP trigger set_timestamp_address on "address";
DROP trigger set_timestamp_user_address on "user_address";
DROP trigger set_timestamp_user_review on "user_review";
DROP trigger set_timestamp_shopping_cart on "shopping_cart";
DROP trigger set_timestamp_shopping_cart_item on "shopping_cart_item";
DROP trigger set_timestamp_wish_list on "wish_list";
DROP trigger set_timestamp_wish_list_item on "wish_list_item";
DROP trigger set_timestamp_shop_order on "shop_order";
DROP trigger set_timestamp_shop_order_item on "shop_order_item";
DROP trigger set_timestamp_product on "product";
DROP trigger set_timestamp_product_item on "product_item";
DROP trigger set_timestamp_order_status on "order_status";
DROP trigger set_timestamp_admin on "admin";
DROP trigger set_timestamp_admin_type on "admin_type";
DROP FUNCTION trigger_set_timestamp();