// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: home_page_text_banner.sql

package db

import (
	"context"

	null "github.com/guregu/null/v5"
)

const createHomePageTextBanner = `-- name: CreateHomePageTextBanner :one
INSERT INTO "home_page_text_banner" (
  name,
  description
) VALUES (
  $1, $2
)
RETURNING id, name, description
`

type CreateHomePageTextBannerParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateHomePageTextBanner(ctx context.Context, arg CreateHomePageTextBannerParams) (HomePageTextBanner, error) {
	row := q.db.QueryRow(ctx, createHomePageTextBanner, arg.Name, arg.Description)
	var i HomePageTextBanner
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const deleteHomePageTextBanner = `-- name: DeleteHomePageTextBanner :exec
DELETE FROM "home_page_text_banner"
WHERE id = $1
`

func (q *Queries) DeleteHomePageTextBanner(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteHomePageTextBanner, id)
	return err
}

const getHomePageTextBanner = `-- name: GetHomePageTextBanner :one
SELECT id, name, description FROM "home_page_text_banner"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHomePageTextBanner(ctx context.Context, id int64) (HomePageTextBanner, error) {
	row := q.db.QueryRow(ctx, getHomePageTextBanner, id)
	var i HomePageTextBanner
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const listHomePageTextBanners = `-- name: ListHomePageTextBanners :many
SELECT id, name, description FROM "home_page_text_banner"
`

func (q *Queries) ListHomePageTextBanners(ctx context.Context) ([]HomePageTextBanner, error) {
	rows, err := q.db.Query(ctx, listHomePageTextBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomePageTextBanner{}
	for rows.Next() {
		var i HomePageTextBanner
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHomePageTextBanner = `-- name: UpdateHomePageTextBanner :one
UPDATE "home_page_text_banner"
SET 
name = COALESCE($1,name),
description = COALESCE($2,description)
WHERE id = $3
RETURNING id, name, description
`

type UpdateHomePageTextBannerParams struct {
	Name        null.String `json:"name"`
	Description null.String `json:"description"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateHomePageTextBanner(ctx context.Context, arg UpdateHomePageTextBannerParams) (HomePageTextBanner, error) {
	row := q.db.QueryRow(ctx, updateHomePageTextBanner, arg.Name, arg.Description, arg.ID)
	var i HomePageTextBanner
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
