// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

type Address struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Name        string    `json:"name"`
	Telephone   string    `json:"telephone"`
	AddressLine string    `json:"address_line"`
	Region      string    `json:"region"`
	City        string    `json:"city"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Admin struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	TypeID    int64     `json:"type_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	LastLogin time.Time `json:"last_login"`
	Active    bool      `json:"active"`
}

type AdminSession struct {
	ID           uuid.UUID `json:"id"`
	AdminID      int64     `json:"admin_id"`
	RefreshToken string    `json:"refresh_token"`
	AdminAgent   string    `json:"admin_agent"`
	ClientIp     string    `json:"client_ip"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	ExpiresAt    time.Time `json:"expires_at"`
	IsBlocked    bool      `json:"is_blocked"`
}

type AdminType struct {
	ID        int64     `json:"id"`
	AdminType string    `json:"admin_type"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type AppPolicy struct {
	ID        int64       `json:"id"`
	Policy    null.String `json:"policy"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type BrandPromotion struct {
	BrandID             int64       `json:"brand_id"`
	PromotionID         int64       `json:"promotion_id"`
	BrandPromotionImage null.String `json:"brand_promotion_image"`
	// default is false
	Active bool `json:"active"`
}

type CategoryPromotion struct {
	CategoryID             int64       `json:"category_id"`
	PromotionID            int64       `json:"promotion_id"`
	CategoryPromotionImage null.String `json:"category_promotion_image"`
	// default is false
	Active bool `json:"active"`
}

type FeaturedProductItem struct {
	ID            int64     `json:"id"`
	ProductItemID int64     `json:"product_item_id"`
	StartDate     time.Time `json:"start_date"`
	EndDate       time.Time `json:"end_date"`
	Priority      null.Int  `json:"priority"`
	Active        bool      `json:"active"`
}

type HomePageTextBanner struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	// default is false
	Active bool `json:"active"`
}

type Notification struct {
	UserID          int64       `json:"user_id"`
	DeviceID        null.String `json:"device_id"`
	FcmToken        null.String `json:"fcm_token"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	DeliveryUpdates bool        `json:"delivery_updates"`
}

type OrderStatus struct {
	ID int64 `json:"id"`
	// values like ordered, processed and delivered
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PaymentMethod struct {
	ID            int64  `json:"id"`
	UserID        int64  `json:"user_id"`
	PaymentTypeID int64  `json:"payment_type_id"`
	Provider      string `json:"provider"`
	IsDefault     bool   `json:"is_default"`
}

type PaymentType struct {
	ID int64 `json:"id"`
	// for companies payment system like BCD
	Value    string `json:"value"`
	IsActive bool   `json:"is_active"`
}

type Product struct {
	ID          int64     `json:"id"`
	CategoryID  int64     `json:"category_id"`
	BrandID     int64     `json:"brand_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	// default is false
	Active bool        `json:"active"`
	Search null.String `json:"search"`
}

type ProductBrand struct {
	ID         int64  `json:"id"`
	BrandName  string `json:"brand_name"`
	BrandImage string `json:"brand_image"`
}

type ProductCategory struct {
	ID               int64    `json:"id"`
	ParentCategoryID null.Int `json:"parent_category_id"`
	CategoryName     string   `json:"category_name"`
	CategoryImage    string   `json:"category_image"`
}

type ProductColor struct {
	ID         int64  `json:"id"`
	ColorValue string `json:"color_value"`
}

type ProductConfiguration struct {
	ProductItemID     int64 `json:"product_item_id"`
	VariationOptionID int64 `json:"variation_option_id"`
}

type ProductImage struct {
	ID            int64  `json:"id"`
	ProductImage1 string `json:"product_image_1"`
	ProductImage2 string `json:"product_image_2"`
	ProductImage3 string `json:"product_image_3"`
}

type ProductItem struct {
	ID         int64     `json:"id"`
	ProductID  int64     `json:"product_id"`
	ImageID    int64     `json:"image_id"`
	ColorID    int64     `json:"color_id"`
	Price      string    `json:"price"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	ProductSku int64     `json:"product_sku"`
	// default is false
	Active bool `json:"active"`
}

type ProductPromotion struct {
	ProductID             int64       `json:"product_id"`
	PromotionID           int64       `json:"promotion_id"`
	ProductPromotionImage null.String `json:"product_promotion_image"`
	// default is false
	Active bool `json:"active"`
}

type ProductSize struct {
	ID            int64  `json:"id"`
	ProductItemID int64  `json:"product_item_id"`
	SizeValue     string `json:"size_value"`
	Qty           int32  `json:"qty"`
}

type Promotion struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	DiscountRate int64     `json:"discount_rate"`
	StartDate    time.Time `json:"start_date"`
	EndDate      time.Time `json:"end_date"`
	// default is false
	Active bool `json:"active"`
}

type ResetPassword struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	SecretCode string    `json:"secret_code"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	ExpiredAt  time.Time `json:"expired_at"`
	IsUsed     bool      `json:"is_used"`
}

type ShippingMethod struct {
	ID int64 `json:"id"`
	// values like normal, or free
	Name  string `json:"name"`
	Price string `json:"price"`
}

type ShopOrder struct {
	ID                int64     `json:"id"`
	TrackNumber       string    `json:"track_number"`
	UserID            int64     `json:"user_id"`
	PaymentTypeID     int64     `json:"payment_type_id"`
	ShippingAddressID null.Int  `json:"shipping_address_id"`
	OrderTotal        string    `json:"order_total"`
	ShippingMethodID  int64     `json:"shipping_method_id"`
	OrderStatusID     null.Int  `json:"order_status_id"`
	AddressName       string    `json:"address_name"`
	AddressTelephone  string    `json:"address_telephone"`
	AddressLine       string    `json:"address_line"`
	AddressRegion     string    `json:"address_region"`
	AddressCity       string    `json:"address_city"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	CompletedAt       time.Time `json:"completed_at"`
	OrderNumber       int32     `json:"order_number"`
}

type ShopOrderItem struct {
	ID            int64 `json:"id"`
	ProductItemID int64 `json:"product_item_id"`
	OrderID       int64 `json:"order_id"`
	// price of product when ordered
	Price string `json:"price"`
	// shipping method price when the order was made
	ShippingMethodPrice string    `json:"shipping_method_price"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
	Quantity            int32     `json:"quantity"`
	// discount of product when ordered
	Discount int32 `json:"discount"`
}

type ShoppingCart struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ShoppingCartItem struct {
	ID             int64     `json:"id"`
	ShoppingCartID int64     `json:"shopping_cart_id"`
	ProductItemID  int64     `json:"product_item_id"`
	SizeID         int64     `json:"size_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Qty            int32     `json:"qty"`
}

type User struct {
	ID               int64     `json:"id"`
	Username         string    `json:"username"`
	Email            string    `json:"email"`
	Password         string    `json:"password"`
	DefaultPayment   null.Int  `json:"default_payment"`
	DefaultAddressID null.Int  `json:"default_address_id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	IsBlocked        bool      `json:"is_blocked"`
	IsEmailVerified  bool      `json:"is_email_verified"`
}

type UserReview struct {
	ID               int64     `json:"id"`
	UserID           int64     `json:"user_id"`
	OrderedProductID int64     `json:"ordered_product_id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	RatingValue      int32     `json:"rating_value"`
}

type UserSession struct {
	ID           uuid.UUID `json:"id"`
	UserID       int64     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	ExpiresAt    time.Time `json:"expires_at"`
	IsBlocked    bool      `json:"is_blocked"`
}

type Variation struct {
	ID         int64 `json:"id"`
	CategoryID int64 `json:"category_id"`
	// variation names like color, and size
	Name string `json:"name"`
}

type VariationOption struct {
	ID          int64    `json:"id"`
	VariationID null.Int `json:"variation_id"`
	// variation values like Red, ans Size XL
	Value string `json:"value"`
}

type VerifyEmail struct {
	ID         int64     `json:"id"`
	UserID     null.Int  `json:"user_id"`
	SecretCode string    `json:"secret_code"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
	IsUsed     bool      `json:"is_used"`
}

type WishList struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WishListItem struct {
	ID            int64     `json:"id"`
	WishListID    int64     `json:"wish_list_id"`
	ProductItemID int64     `json:"product_item_id"`
	SizeID        int64     `json:"size_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
