// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: product_item.sql

package db

import (
	"context"
	"database/sql"
)

const createProductItem = `-- name: CreateProductItem :one
INSERT INTO "product_item" (
  product_id,
  product_sku,
  qty_in_stock,
  product_image,
  price,
  active
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, product_id, product_sku, qty_in_stock, product_image, price, active, created_at, updated_at
`

type CreateProductItemParams struct {
	ProductID    int64  `json:"product_id"`
	ProductSku   int64  `json:"product_sku"`
	QtyInStock   int32  `json:"qty_in_stock"`
	ProductImage string `json:"product_image"`
	Price        string `json:"price"`
	Active       bool   `json:"active"`
}

func (q *Queries) CreateProductItem(ctx context.Context, arg CreateProductItemParams) (ProductItem, error) {
	row := q.db.QueryRowContext(ctx, createProductItem,
		arg.ProductID,
		arg.ProductSku,
		arg.QtyInStock,
		arg.ProductImage,
		arg.Price,
		arg.Active,
	)
	var i ProductItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductSku,
		&i.QtyInStock,
		&i.ProductImage,
		&i.Price,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductItem = `-- name: DeleteProductItem :exec
DELETE FROM "product_item"
WHERE id = $1
`

func (q *Queries) DeleteProductItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductItem, id)
	return err
}

const getProductItem = `-- name: GetProductItem :one
SELECT id, product_id, product_sku, qty_in_stock, product_image, price, active, created_at, updated_at FROM "product_item"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductItem(ctx context.Context, id int64) (ProductItem, error) {
	row := q.db.QueryRowContext(ctx, getProductItem, id)
	var i ProductItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductSku,
		&i.QtyInStock,
		&i.ProductImage,
		&i.Price,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductItems = `-- name: ListProductItems :many
SELECT id, product_id, product_sku, qty_in_stock, product_image, price, active, created_at, updated_at FROM "product_item"
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListProductItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProductItems(ctx context.Context, arg ListProductItemsParams) ([]ProductItem, error) {
	rows, err := q.db.QueryContext(ctx, listProductItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductItem{}
	for rows.Next() {
		var i ProductItem
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductSku,
			&i.QtyInStock,
			&i.ProductImage,
			&i.Price,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductItem = `-- name: UpdateProductItem :one
UPDATE "product_item"
SET
product_id = COALESCE($1,product_id),
product_sku = COALESCE($2,product_sku),
qty_in_stock = COALESCE($3,qty_in_stock),
product_image = COALESCE($4,product_image),
price = COALESCE($5,price),
active = COALESCE($6,active)
WHERE id = $7
RETURNING id, product_id, product_sku, qty_in_stock, product_image, price, active, created_at, updated_at
`

type UpdateProductItemParams struct {
	ProductID    sql.NullInt64  `json:"product_id"`
	ProductSku   sql.NullInt64  `json:"product_sku"`
	QtyInStock   sql.NullInt32  `json:"qty_in_stock"`
	ProductImage sql.NullString `json:"product_image"`
	Price        sql.NullString `json:"price"`
	Active       sql.NullBool   `json:"active"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateProductItem(ctx context.Context, arg UpdateProductItemParams) (ProductItem, error) {
	row := q.db.QueryRowContext(ctx, updateProductItem,
		arg.ProductID,
		arg.ProductSku,
		arg.QtyInStock,
		arg.ProductImage,
		arg.Price,
		arg.Active,
		arg.ID,
	)
	var i ProductItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductSku,
		&i.QtyInStock,
		&i.ProductImage,
		&i.Price,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
