// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: user.sql

package db

import (
	"context"
	"time"

	"github.com/guregu/null"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (
  username,
  email,
  password,
  telephone,
  default_payment
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, username, email, password, telephone, default_payment, created_at, updated_at
`

type CreateUserParams struct {
	Username       string   `json:"username"`
	Email          string   `json:"email"`
	Password       string   `json:"password"`
	Telephone      int32    `json:"telephone"`
	DefaultPayment null.Int `json:"default_payment"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Telephone,
		arg.DefaultPayment,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Telephone,
		&i.DefaultPayment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserWithCart = `-- name: CreateUserWithCart :one
WITH t1 AS(
INSERT INTO "user" (
  username,
  email,
  password,
  telephone,
  default_payment
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, username, email, password, telephone, default_payment, created_at, updated_at
),
t2 AS(
  INSERT INTO "shopping_cart" (
  user_id
) VALUES ((Select id from t1))
)

SELECT id, username, email, password, telephone, default_payment, created_at, updated_at FROM t1
`

type CreateUserWithCartParams struct {
	Username       string   `json:"username"`
	Email          string   `json:"email"`
	Password       string   `json:"password"`
	Telephone      int32    `json:"telephone"`
	DefaultPayment null.Int `json:"default_payment"`
}

type CreateUserWithCartRow struct {
	ID             int64     `json:"id"`
	Username       string    `json:"username"`
	Email          string    `json:"email"`
	Password       string    `json:"password"`
	Telephone      int32     `json:"telephone"`
	DefaultPayment null.Int  `json:"default_payment"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) CreateUserWithCart(ctx context.Context, arg CreateUserWithCartParams) (CreateUserWithCartRow, error) {
	row := q.db.QueryRow(ctx, createUserWithCart,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Telephone,
		arg.DefaultPayment,
	)
	var i CreateUserWithCartRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Telephone,
		&i.DefaultPayment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user"
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password, telephone, default_payment, created_at, updated_at FROM "user"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Telephone,
		&i.DefaultPayment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, telephone, default_payment, created_at, updated_at FROM "user"
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Telephone,
		&i.DefaultPayment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password, telephone, default_payment, created_at, updated_at FROM "user"
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Telephone,
			&i.DefaultPayment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user"
SET 
username = COALESCE($1,username),
email = COALESCE($2,email),
password = COALESCE($3,password),
telephone = COALESCE($4,telephone),
default_payment = COALESCE($5,default_payment)
WHERE id = $6
RETURNING id, username, email, password, telephone, default_payment, created_at, updated_at
`

type UpdateUserParams struct {
	Username       null.String `json:"username"`
	Email          null.String `json:"email"`
	Password       null.String `json:"password"`
	Telephone      null.Int    `json:"telephone"`
	DefaultPayment null.Int    `json:"default_payment"`
	ID             int64       `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Telephone,
		arg.DefaultPayment,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Telephone,
		&i.DefaultPayment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
