// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: user.sql

package db

import (
	"context"
	"time"

	"github.com/guregu/null"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (
  username,
  email,
  password,
  telephone,
  is_blocked,
  default_payment
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, username, email, password, telephone, is_blocked, default_payment, created_at, updated_at
`

type CreateUserParams struct {
	Username       string   `json:"username"`
	Email          string   `json:"email"`
	Password       string   `json:"password"`
	Telephone      int32    `json:"telephone"`
	IsBlocked      bool     `json:"is_blocked"`
	DefaultPayment null.Int `json:"default_payment"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Telephone,
		arg.IsBlocked,
		arg.DefaultPayment,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Telephone,
		&i.IsBlocked,
		&i.DefaultPayment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserWithCartAndWishList = `-- name: CreateUserWithCartAndWishList :one
WITH t1 AS(
INSERT INTO "user" (
  username,
  email,
  password,
  telephone,
  is_blocked,
  default_payment
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, username, email, password, telephone, is_blocked, default_payment, created_at, updated_at
),
t2 AS(
  INSERT INTO "shopping_cart" (
  user_id
) VALUES ((Select id from t1))
  RETURNING id
),
t3 AS(
  INSERT INTO "wish_list" (
    user_id
) VALUES ((Select id from t1))
  RETURNING id
)

SELECT t1.id, t1.username, t1.email, t1.password, t1.telephone, t1.is_blocked, t1.default_payment, t1.created_at, t1.updated_at, t2.id AS shopping_cart_id, t3.id AS wish_list_id FROM t1, t2, t3
`

type CreateUserWithCartAndWishListParams struct {
	Username       string   `json:"username"`
	Email          string   `json:"email"`
	Password       string   `json:"password"`
	Telephone      int32    `json:"telephone"`
	IsBlocked      bool     `json:"is_blocked"`
	DefaultPayment null.Int `json:"default_payment"`
}

type CreateUserWithCartAndWishListRow struct {
	ID             int64     `json:"id"`
	Username       string    `json:"username"`
	Email          string    `json:"email"`
	Password       string    `json:"password"`
	Telephone      int32     `json:"telephone"`
	IsBlocked      bool      `json:"is_blocked"`
	DefaultPayment null.Int  `json:"default_payment"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	ShoppingCartID int64     `json:"shopping_cart_id"`
	WishListID     int64     `json:"wish_list_id"`
}

func (q *Queries) CreateUserWithCartAndWishList(ctx context.Context, arg CreateUserWithCartAndWishListParams) (CreateUserWithCartAndWishListRow, error) {
	row := q.db.QueryRow(ctx, createUserWithCartAndWishList,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Telephone,
		arg.IsBlocked,
		arg.DefaultPayment,
	)
	var i CreateUserWithCartAndWishListRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Telephone,
		&i.IsBlocked,
		&i.DefaultPayment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShoppingCartID,
		&i.WishListID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM "user"
WHERE id = $1
RETURNING id, username, email, password, telephone, is_blocked, default_payment, created_at, updated_at
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Telephone,
		&i.IsBlocked,
		&i.DefaultPayment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password, telephone, is_blocked, default_payment, created_at, updated_at FROM "user"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Telephone,
		&i.IsBlocked,
		&i.DefaultPayment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.username, u.email, u.password, u.telephone, u.is_blocked, u.default_payment, u.created_at, u.updated_at, sc.id AS shop_cart_id, wl.id AS wish_list_id FROM "user" AS u
LEFT JOIN shopping_cart AS sc ON sc.user_id = u.id
LEFT JOIN wish_list AS wl ON wl.user_id = u.id
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID             int64     `json:"id"`
	Username       string    `json:"username"`
	Email          string    `json:"email"`
	Password       string    `json:"password"`
	Telephone      int32     `json:"telephone"`
	IsBlocked      bool      `json:"is_blocked"`
	DefaultPayment null.Int  `json:"default_payment"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	ShopCartID     null.Int  `json:"shop_cart_id"`
	WishListID     null.Int  `json:"wish_list_id"`
}

// SELECT * FROM "user"
// WHERE email = $1 LIMIT 1;
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Telephone,
		&i.IsBlocked,
		&i.DefaultPayment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShopCartID,
		&i.WishListID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password, telephone, is_blocked, default_payment, created_at, updated_at FROM "user"
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Telephone,
			&i.IsBlocked,
			&i.DefaultPayment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user"
SET 
username = COALESCE($1,username),
email = COALESCE($2,email),
password = COALESCE($3,password),
telephone = COALESCE($4,telephone),
default_payment = COALESCE($5,default_payment),
updated_at = now()
WHERE id = $6
RETURNING id, username, email, password, telephone, is_blocked, default_payment, created_at, updated_at
`

type UpdateUserParams struct {
	Username       null.String `json:"username"`
	Email          null.String `json:"email"`
	Password       null.String `json:"password"`
	Telephone      null.Int    `json:"telephone"`
	DefaultPayment null.Int    `json:"default_payment"`
	ID             int64       `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Telephone,
		arg.DefaultPayment,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Telephone,
		&i.IsBlocked,
		&i.DefaultPayment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
