name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Run unit tests
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: CShop 

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to the container registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/cshop:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/cshop:${{ github.sha }}